# Generated by Django 5.0.1 on 2024-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clint",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("ProfileUpdated", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                ("about", models.CharField(blank=True, max_length=255, null=True)),
                ("ProfileUpdated", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
            ],
        ),
    ]
