# Generated by Django 5.0.1 on 2024-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="experence",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="patents",
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor", name="rating", field=models.IntegerField(default=1),
        ),
    ]
