# Generated by Django 5.0.1 on 2024-10-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_doctor_experence_doctor_patents_doctor_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.clint"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.CharField(max_length=200)),
                ("SendFrom", models.IntegerField()),
                ("ViewStatus", models.IntegerField(default=0)),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "Room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.room"
                    ),
                ),
            ],
        ),
    ]
