# Generated by Django 5.0.1 on 2024-10-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_room_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("booktime", models.DateField()),
                ("timesloat", models.IntegerField()),
                ("rate", models.FloatField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "Room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.room",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.clint"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.doctor"
                    ),
                ),
            ],
        ),
    ]
