# Generated by Django 5.0.1 on 2024-10-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_bookdoctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdoctor", old_name="booktime", new_name="bookdate",
        ),
    ]
