# Generated by Django 5.1 on 2025-01-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_logined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clint",
            name="api_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
